"""empty message

Revision ID: 6b5936e002fe
Revises: aa3097eeb005
Create Date: 2025-04-03 03:31:06.419696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5936e002fe'
down_revision: Union[str, None] = 'aa3097eeb005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_links_card_id_fkey', 'card_links', type_='foreignkey')
    op.create_foreign_key(None, 'card_links', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.add_column('cards', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('cards_roadmap_id_fkey', 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'roadmaps', ['roadmap_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cards', 'card_id')
    op.add_column('roadmaps', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('roadmaps_owner_id_fkey', 'roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'roadmaps', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('roadmaps', 'roadmap_id')
    op.drop_constraint('user_cards_card_id_fkey', 'user_cards', type_='foreignkey')
    op.drop_constraint('user_cards_user_id_fkey', 'user_cards', type_='foreignkey')
    op.create_foreign_key(None, 'user_cards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_cards', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_roadmaps', 'background',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'your_default_roadmap_background_from_MinIo'"),
               existing_nullable=False)
    op.drop_constraint('user_roadmaps_user_id_fkey', 'user_roadmaps', type_='foreignkey')
    op.drop_constraint('user_roadmaps_roadmap_id_fkey', 'user_roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'user_roadmaps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roadmaps', 'roadmaps', ['roadmap_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'your_default_user_avatar_name_from_MinIo'"),
               existing_nullable=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'1d8522d6-4b3c-4175-a294-c257a6dbb996.jpg'::character varying"),
               existing_nullable=True)
    op.drop_column('users', 'id')
    op.drop_constraint(None, 'user_roadmaps', type_='foreignkey')
    op.drop_constraint(None, 'user_roadmaps', type_='foreignkey')
    op.create_foreign_key('user_roadmaps_roadmap_id_fkey', 'user_roadmaps', 'roadmaps', ['roadmap_id'], ['roadmap_id'], ondelete='CASCADE')
    op.create_foreign_key('user_roadmaps_user_id_fkey', 'user_roadmaps', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('user_roadmaps', 'background',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'1d8522d6-4b3c-4175-a294-c257a6dbb996.jpg'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'user_cards', type_='foreignkey')
    op.drop_constraint(None, 'user_cards', type_='foreignkey')
    op.create_foreign_key('user_cards_user_id_fkey', 'user_cards', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('user_cards_card_id_fkey', 'user_cards', 'cards', ['card_id'], ['card_id'], ondelete='CASCADE')
    op.add_column('roadmaps', sa.Column('roadmap_id', sa.INTEGER(), server_default=sa.text("nextval('roadmaps_roadmap_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.create_foreign_key('roadmaps_owner_id_fkey', 'roadmaps', 'users', ['owner_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('roadmaps', 'id')
    op.add_column('cards', sa.Column('card_id', sa.INTEGER(), server_default=sa.text("nextval('cards_card_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key('cards_roadmap_id_fkey', 'cards', 'roadmaps', ['roadmap_id'], ['roadmap_id'], ondelete='CASCADE')
    op.drop_column('cards', 'id')
    op.drop_constraint(None, 'card_links', type_='foreignkey')
    op.create_foreign_key('card_links_card_id_fkey', 'card_links', 'cards', ['card_id'], ['card_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
